### ISSUE TITLE
crates publishing team

### ISSUE THREAD

**Issue by michaelkirk** [georust/transitfeed#20]
👋 Hi @bfrog, you are the only "user-owner" of the [transitfeed crate on crates.io](https://crates.io/crates/transitfeed), so only you can edit that crate's owners on crates.io.

Following up on https://github.com/georust/meta/pull/21, I created a new [transitfeed-publishers team](https://github.com/orgs/georust/teams/transitfeed-publishers) for publishing to crates.io with you as the sole member and maintainer. 

Could you please [update the crate owners](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner)? Specifically:

---

- [ ] update **transitfeed crate** owners on crates.io:

```
cd transitfeed

# 💥 remove large publishing group
cargo owner --remove github:georust:core

# 🔐 add small publishing group
cargo owner --add github:georust:transitfeed-publishers

# you're currently the only user-owner of the crate. Consider adding another user-owner, 
# that way if for some reason you become inaccessible we have someone else who can edit the owners. 
# See https://github.com/rust-lang/crates.io/issues/2906
cargo owner --add <username>

# make sure everything looks good 👀 
cargo owner --list
```
---

If there's anyone else you'd like to be able to publish the crate, feel free to add them to your publishing team, or as a user-owner. Consider that user-owners, as opposed to owners-via-team, can themselves edit the crate's owners, which could be desirable, or not, depending.

In particular, it looks like @medwards has been actively contributing to GH. Once you switch the publishing team, @medwards (or anyone else) will no longer be able to publish until either they are added back to the new publishing team or added as a user owner.

Let me know if you have any questions, or you can review https://github.com/georust/meta/pull/21.

**Comment by bfrog** [comment]
I've done the above, and added michaelkirk as a user-owner, I don't know if medwards has a crates.io account, cargo complained.

Cheers!
